In [ ]:
import numpy as np
import sys
print(f"numpy version:{np.__version__}")

In [ ]:
flatten = matrix_2d.flatten()
print("\nflattened array back to 1d:",flattened)

In [ ]:
print("hello khushboo")

In [ ]:
np.arange(0,10,2)

In [ ]:
np.ones((2,3),dtype=int)

In [ ]:
float_arr=np.array([1,2,3],dtype=np.float64)
print(float_arr)
print(float_arr.dtype)

In [ ]:
list2=[[1,2,3],
       [4,5,6],
       [7,8,9]]
arr2d=np.array(list2)
print(list2)
print(arr2d)

In [ ]:
import numpy as np
list1=[10,20,30,40,50]
arr=np.array(list1)
print(arr)
print(list1)

In [ ]:
import numpy as np
np.linspace(1,5,20)

In [ ]:
np.eye(4)

In [ ]:
import numpy as np
my_matrix=np.array([[1,2,3],[4,5,6]],dtype=np.int32)
print(my_matrix.ndim)
print(my_matrix.shape)
print(my_matrix.size)
print(my_matrix.itemsize)


In [ ]:
arr=np.array([10,20,30,40,50])
arr[2]
arr[-2]=600
arr[2:4]


In [ ]:
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])
matrix[2,2]

In [ ]:
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])
matrix[0:2,0:2]

In [38]:
arr=np.zeros((3,3))
arr[1,1]=1
arr[0,0]=1
arr[2,0]=1
arr[2,2]=1
arr[0,2]=1
print(arr)

[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]]


In [42]:
data=np.arange(0,21)
data[data%2==0]

#arr indexing
arr1=np.arange(0,21,1)
print(arr1%2==0)
arr1[arr1%2==0]


[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])