In [1]:
import numpy as np
student_data=np.array([
    [90,87,56,34],
    [98,56,24,65],
    [76,87,11,45],
    [56,45,56,54]
])
x=student_data[:,0:3]
print(x)

[[90 87 56]
 [98 56 24]
 [76 87 11]
 [56 45 56]]


In [3]:
student_data=np.array([
    [90,87,56,34],
    [98,56,24,65],
    [76,87,11,45],
    [56,45,56,54]
])
attendance=student_data[:,0]
print(attendance)
internal_score=student_data[:,1]
print(internal_score)
ours_studied=student_data[:,2]
print(ours_studied)

[90 98 76 56]
[87 56 87 45]
[56 24 11 56]


In [4]:
#np.where fix any wrong thing using boolean 
salaries=np.array([20000,50000,30000,40000,-37000,-89000])
new=np.where(salaries<0,0,salaries)
print(new)


[20000 50000 30000 40000     0     0]


In [5]:
import numpy as np
data=np.array([5,12,8,21,3,14,7])
print (data>10)
data[data>10]

[False  True False  True False  True False]


array([12, 21, 14])

In [2]:
import numpy as np
x=np.array([10,40,30,60])
print(np.mean(x))

35.0


In [9]:
x=np.array([
    [10.0,200.0],
    [30.0,100.0],
    [20.0,300.0]
])
print(np.mean(x,axis=0))
print(np.mean(x,axis=1))
#axis=0 is used for coloum
#axis=1 is used for rows

[ 20. 200.]
[105.  65. 160.]


In [10]:
#reshaping or flatterning
import numpy as np
flat_arr=np.arange(6)
print("original 1d array:",flat_arr)
matrix_2d=flat_arr.reshape(2,3)
print(matrix_2d)
flattend = matrix_2d.flatten()
print("\nflattened array back to 1d:",flattend)

original 1d array: [0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]

flattened array back to 1d: [0 1 2 3 4 5]


In [11]:
inputs=np.array([1.0,2.0])
weights=np.array([
    [0.2,0.8,-0.5],
    [0.5,-0.1,0.4]
])
print(np.dot(inputs,weights))

[1.2 0.6 0.3]


In [12]:
inputs=np.array([1.0,2.0])
print(inputs+5)
print(inputs*5)

[6. 7.]
[ 5. 10.]


In [13]:
age=np.array([25,67,89,-56,-99,999])
new=np.where((age<0,)|(age>120),30,age)
print (new)

[[25 67 89 30 30 30]]
